### PR TITLE
Improve performance 3

### PR DESCRIPTION
**Pull request by dawidreedsy**
This PR combines few changes:
- Extract performance updatgade from [admin app](https://github.com/reedsy/reedsy-editor-admin/blob/a3ebb5d13d0adf7441d324928ad84804edd3ac0e/src/services/adminjs/resources/utilities/patch-find-one.ts#L1-L48)
- Fixes mongoose 8 bump bug

### CODE REVIEW

**Comment by dawidreedsy** [comment]
@alecgibson
I split changes in to commits, to save time, but if you want I can prepare separate PRs

**Comment by alecgibson** [comment]
Yeah @dawidreedsy there's a lot of noise in this PR. Please at least split the CI-related stuff into a separate PR, and then sort out the whitespace noise in the rest of the PR please.

**Comment by alecgibson** [comment]
Also a better PR title please

**Comment by dawidreedsy** [comment]
Split into:
- https://github.com/reedsy/adminjs-mongoose/pull/8
- https://github.com/reedsy/adminjs-mongoose/pull/12

**Pull request closed without merging**
